// The page shell every rendered page shares.
//
// The navigation is one entry per type in the grammar, in the order the
// grammar declares them. Adding a type to schema.yaml adds it to the
// navigation; there is no list of links to keep in sync.

import { html } from "./html.mjs";
import { display, types } from "./display.mjs";

const STYLE = `
      :root { color-scheme: light dark; }
      body {
        max-width: 42rem;
        margin: 0 auto;
        padding: 2rem 1.25rem 6rem;
        font: 1rem/1.65 ui-serif, Georgia, serif;
      }
      nav { font-family: ui-sans-serif, system-ui, sans-serif; font-size: .85rem; }
      nav a { margin-right: 1rem; }
      h1 { font-size: 1.4rem; }
      h2 { font-size: 1.15rem; }
      hr { border: 0; border-top: 1px solid; opacity: .25; margin: 3rem 0; }
      dl { font-family: ui-sans-serif, system-ui, sans-serif; font-size: .85rem; }
      dt { opacity: .6; }
      dd { margin: 0 0 .5rem; }
      pre { white-space: pre-wrap; }
`;

export const layout = (ctx, title, main) => html`<!doctype html>
<!-- Generated by codex/render.mjs from schema.yaml. Do not edit. -->
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${title === "Gravity" ? title : `${title} — Gravity`}</title>
    <style>${STYLE}    </style>
  </head>
  <body>
    <header>
      <h1><a href="${ctx.href("index.html")}">Gravity</a></h1>
      <nav>
${types(ctx.schema).map(
  (t) =>
    html`        <a href="${ctx.href(display(ctx.schema, t).index)}">${display(ctx.schema, t).plural}</a>\n`,
)}      </nav>
    </header>

    <main>
${main}
    </main>
  </body>
</html>
`;
